config/routes.rb
Bounenkai::Application.routes.draw do

  resources :events, except: [:index, :create, :update] do
    member do
      post :bulk_create
    end

    resources :event_steps

    resources :members, except: [:index, :show, :create, :update] do
      resources :member_steps
    end
  end

  resources :top, only: :index

  root 'top#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  acts_as_paranoid

  validates :name,
            :tweet,
            presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  acts_as_paranoid

  has_many :members, dependent: :destroy
  has_many :boards, dependent: :destroy
  has_many :schedule_dates, dependent: :destroy
  has_many :schedule_places, dependent: :destroy

  accepts_nested_attributes_for :schedule_dates
  accepts_nested_attributes_for :schedule_places
end

app/models/hope_date.rb
class HopeDate < ActiveRecord::Base
  acts_as_paranoid
end

app/models/hope_place.rb
class HopePlace < ActiveRecord::Base
  acts_as_paranoid
end

app/models/member.rb
class Member < ActiveRecord::Base
  acts_as_paranoid
end

app/models/schedule_date.rb
class ScheduleDate < ActiveRecord::Base
  acts_as_paranoid

  validates :date,
            presence: true
end

app/models/schedule_place.rb
class SchedulePlace < ActiveRecord::Base
  acts_as_paranoid

  validates :name,
            :address,
            :price,
            presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/event_steps_controller.rb
class EventStepsController < ApplicationController
  include Wicked::Wizard
  steps :planner, :detail, :date, :place, :mail
  before_action :set_event, only: [:show, :update]

  def show
    render_wizard
  end

  def update
    if params[:add].present?
      @event.update_attributes(event_params)
      @event.schedule_dates.build if step == :date
      @event.schedule_places.build if step == :place
      render step
    elsif step == steps.last
      # SendMail.invitation(@event.id, params[:mail_address]).deliver if params[:send].present?
      redirect_to event_url(@event), notice: "登録しました。"
    else
      @event.update_attributes(event_params)
      render_wizard @event
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:event_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      # params[:event]
      params.require(:event).permit(:name, :detail, :planner, :password, :close_date, {schedule_dates_attributes: [:id, :date]}, {schedule_places_attributes: [:id, :name, :address, :price]})
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :destroy, :bulk_create]

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    if @event.save
      redirect_to event_event_steps_url(@event)
    else
      redirect_to top_index_url
    end
  end

  # GET /events/1/edit
  def edit
    redirect_to event_event_steps_url(@event)
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to top_index_url }
      format.json { head :no_content }
    end
  end

  def bulk_create
    @board = @event.boards.build(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @event, notice: '投稿しました。'}
        format.json { render action: 'show', status: :created, location: @board }
      else
        format.html { render action: 'show' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      # params[:event]
      params.require(:event).permit(:name, :detail, :planner, :password, :close_date)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :tweet)
    end
end

app/controllers/member_steps_controller.rb
class MemberStepsController < ApplicationController
  include Wicked::Wizard
  steps :member, :date, :place
  before_action :set_event, only: [:show, :update]
  before_action :set_member, only: [:show, :update]

  def show
    render_wizard
  end

  def update
    if params[:add].present?
      # @event.update_attributes(event_params)
      # @event.schedule_dates.build if step == :date
      # @event.schedule_places.build if step == :place
      # render step
    elsif step == steps.last
      # SendMail.invitation(@event.id, params[:mail_address]).deliver if params[:send].present?
      redirect_to event_url(@event), notice: "登録しました。"
    else
      @member.update_attributes(member_params)
      render_wizard @member
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:event_id])
    end

    def set_member
      @member = Member.find(params[:member_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      # params[:member]
      params.require(:member).permit(:name, :password, {hope_dates_attributes: [:id, :schedule_date_id]}, {hope_places_attributes: [:id, :schedule_place_id]})
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_event, only: [:new, :edit, :destroy]
  before_action :set_member, only: [:edit, :destroy]

  # GET /members/new
  def new
    @member = @event.members.build
    if @member.save
      redirect_to event_member_member_steps_url(@event, @member)
    else
      redirect_to event_path_url(@event)
    end
  end

  # GET /members/1/edit
  def edit
    redirect_to event_member_member_steps_url(@event, @member)
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to Event.find(params[:event_id])}
      format.json { head :no_content }
    end
  end

  private
    # use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:event_id])
    end

    # use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params[:member]
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_steps_helper.rb
module EventStepsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/member_steps_helper.rb
module MemberStepsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/event_steps/date.html.haml
= simple_form_for @event, :url => wizard_path, :method => :put do |f|

  %table.tabl.table-condensede
    - @event.schedule_dates.build if @event.schedule_dates.count == 0
    = f.simple_fields_for :schedule_dates do |d|
      %tr
        %td{nowrap: "nowrap"}
          = d.input :date, include_blank: true

  .form-actions
    = f.submit '日付を追加する', class: 'btn btn-default', name: 'add'
    = f.submit '次へ', class: 'btn btn-primary'

app/views/event_steps/detail.html.haml
= simple_form_for @event, :url => wizard_path, :method => :put do |f|
  = f.input :name, required: true
  = f.input :detail, required: true
  = f.input :close_date, required: true

  .form-actions
    = f.submit '次へ', class: 'btn btn-primary'

app/views/event_steps/mail.html.haml
= simple_form_for @event, :url => wizard_path, :method => :put do |f|
  = text_area_tag :mail_address

  .form-actions
    = f.submit 'メール送信して登録完了', class: 'btn btn-warning', name: 'send'
    = f.submit 'メール送信せずに登録完了', class: 'btn btn-primary'

app/views/event_steps/place.html.haml
= simple_form_for @event, :url => wizard_path, :method => :put do |f|

  %table.tabl.table-condensede
    - @event.schedule_places.build if @event.schedule_places.count == 0
    = f.simple_fields_for :schedule_places do |p|
      %tr
        %td
          = p.input :name
        %td
          = p.input :address
        %td
          = p.input :price

  .form-actions
    = f.submit '場所を追加する', class: 'btn btn-default', name: 'add'
    = f.submit '次へ', class: 'btn btn-primary'

app/views/event_steps/planner.html.haml
= simple_form_for @event, :url => wizard_path, :method => :put do |f|
  = f.input :planner, required: true
  = f.input :password, required: true

  .form-actions
    = f.submit '次へ', class: 'btn btn-primary'

app/views/events/_form.html.haml
= simple_form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  = f.input :name
  = f.input :detail
  = f.input :planner
  = f.input :password

  .actions
    = f.submit '登録', class: 'btn btn-primary'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events

%table
  %tr
    %th
    %th
    %th

  - @events.each do |event|
    %tr
      %td= link_to 'Show', event
      %td= link_to 'Edit', edit_event_path(event)
      %td= link_to 'Destroy', event, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 新しいイベントを作る

= render 'form'

= link_to 'TOPに戻る', top_index_path, class: 'btn btn-default'

app/views/events/show.html.haml
%h1= @event.name
企画者
= @event.planner
%br
%br

.alert.alert-info
  %h3 ■イベント
  %br
  .white_back
    = @event.detail
  %br
  = link_to 'イベント内容を編集する(要パスワード)', edit_event_path(@event), class: 'btn btn-warning'
  = link_to 'このイベントに参加する', new_event_member_path(@event), class: 'btn btn-success'

%br

.alert.alert-info
  %h3 ■日程
  %br
  %table.table-bordered.max_width.white_back
    %tr
      %th 参加者名
      %th 希望日１
      %th 希望日２
      %th 希望日３
    - @event.members.each do |member|
      %tr
        %td
        %td
        %td
        %td
    %tr
      %td
      %td
      %td
      %td

%br

.alert.alert-info
  %h3 ■場所
  %br
  %table.table-bordered.max_width.white_back
    %tr
      %th 参加者名
      %th 希望場所１
      %th 希望場所２
      %th 希望場所３
    - @event.members.each do |member|
      %tr
        %td
        %td
        %td
        %td
    %tr
      %td
      %td
      %td
      %td

%br

.alert.alert-info
  %h3 ■掲示板
  %br
  %table.table-bordered.max_width.white_back
    - if @event.boards.present?
      - @event.boards.each do |board|
        %tr
          %td
            投稿者
            = board.name
            %br
            = board.tweet
    - else
      %tr
        %td
          投稿はありません。

  %br

.alert.alert-info
  %h3 ■投稿欄
  %br
  - @board = @event.boards.build
  = simple_form_for @board, url: bulk_create_event_path do |f|
    - if @board.errors.any?
      #error_explanation
        %h2= "#{pluralize(@board.errors.count, "error")} prohibited this board from being saved:"
        %ul
          - @board.errors.full_messages.each do |msg|
            %li= msg

    = f.input :name, input_html: { class: 'max_width' }
    = f.input :tweet, input_html: { class: 'max_width' }

    .actions
      = f.submit '投稿', class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : Settings.app_name
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
              %a.brand(href=top_index_path)
                = Settings.app_name
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container

      .row
        .span9
          = bootstrap_flash
          %br
          %br
          %br
          = yield
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

      %footer
        %br
        %p &copy; SakurazukaApps 2014

app/views/member_steps/date.html.haml
= simple_form_for @member, :url => wizard_path, :method => :put do |f|

  暫定：
  = f.input :name, required: true

  .form-actions
    = f.submit '次へ', class: 'btn btn-primary'

app/views/member_steps/member.html.haml
= simple_form_for @member, :url => wizard_path, :method => :put do |f|
  = f.input :name, required: true
  = f.input :password, required: true

  .form-actions
    = f.submit '次へ', class: 'btn btn-primary'

app/views/member_steps/place.html.haml
= simple_form_for @event, :url => wizard_path, :method => :put do |f|

  暫定：
  = f.input :name, required: true

  .form-actions
    = f.submit '次へ', class: 'btn btn-primary'

app/views/members/_form.html.haml
= form_for @member do |f|
  - if @member.errors.any?
    #error_explanation
      %h2= "#{pluralize(@member.errors.count, "error")} prohibited this member from being saved:"
      %ul
        - @member.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/members/edit.html.haml
%h1 Editing member

= render 'form'

= link_to 'Show', @member
\|
= link_to 'Back', members_path

app/views/members/index.html.haml
%h1 Listing members

%table
  %tr
    %th
    %th
    %th

  - @members.each do |member|
    %tr
      %td= link_to 'Show', member
      %td= link_to 'Edit', edit_member_path(member)
      %td= link_to 'Destroy', member, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Member', new_member_path

app/views/members/new.html.haml
%h1 New member

= render 'form'

= link_to 'Back', members_path

app/views/members/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_member_path(@member)
\|
= link_to 'Back', members_path

app/views/send_mail/invitation.text.haml
SendMail#invitation

= @greeting + ", find me in app/views/send_mail/invitation.text.haml"

app/views/top/index.html.haml
%h1 日程＆場所調整くん！
%br

= link_to '新しいイベントを作る', new_event_path, class: 'btn btn-primary'